### ISSUE TITLE
SMOK alien

### ISSUE THREAD

**Issue by Dil3mm4** [MicroSur/sur_myevic#33]
If you'd like to add SMOK support, I could lend an hand, since I own a SMOK alien 220. :)

**Comment by arafey** [comment]
myevic based firmware support the Nuvoton NuMicro M451 Series (ARM Cortex-M4F). If your device uses this, then it may be possible.

**Comment by Dil3mm4** [comment]
http://www.nuvoton.com/hq/products/microcontrollers/arm-cortex-m0-mcus/nuc120-122-123-220-usb-series/nuc220le3an?__locale=en

That's the one inside the smok alien 220.

**Comment by arafey** [comment]
I think you'll have a hard time getting it to work. But this is how I would approach it: you'll need to learn some specifics for your device and create entries in multiple files (e.g. [events.c](https://github.com/MicroSur/sur_myevic/blob/master/src/events.c)).

If you get that part right, then assuming there is nothing that relies on Cortex-M4F specific features like the hardware FPU, then you can try compiling for your device using [these instructions] (https://github.com/MicroSur/sur_myevic/blob/master/git_doc_en/howtobuild_en.md). There is one exception to those instructions in your case, you need to use the nuSDK for NUC220 rather than M451. If you're lucky, there is a 1 to 1 mapping between the two SDKs. Otherwise, you'll need to work your way through the various errors you get. I suspect you'll also need to make some changes to Makefile and linker.ld because they reference some specific things such as CPU architecture, FPU model, and APROM size, among other things. 

I can't really judge the feasibility, but it should be possible if given enough time, resources, and effort.

**Comment by arafey** [comment]
I should add that this is a starting point, there are probably other compounding factors I'm forgetting about, but hopefully you have enough info to start working or consider alternatives.

**Comment by Dil3mm4** [comment]
> I can't really judge the feasibility, but it should be possible if given enough time, resources, and effort.

That's the point, I don't have enough time for it. 
My work stresses my out a lot and this will add some extra stress.
I guess I'll just switch the mod. 📦

**Comment by arafey** [comment]
I think it would be cool to have wider compatibility, but it is a major undertaking. Also heads up, the Russian compatibility list is probably more up to date than the English one.

**Comment by MicroSur** [comment]
Russian readme is up to date, english is not. U can help with translate. Good vape!
